version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
      - /app/node_modules
      - ./package.json:/app/package.json
    depends_on:
      - mongo
      - redis
    environment:
      - LOGGING=true
      - MONGO_URL=mongodb://mongo/l3ifhack
      - REDIS=redis://redis:6379
      - TOKEN_SECRET=TOKENSECRET
    command: node ./node_modules/.bin/nodemon --legacy-watch --watch server.js --watch api server.js
  mongo:
    image: mvertes/alpine-mongo
  redis:
    image: redis:4-alpine